### ISSUE TITLE
ssh reports unsupported options

### ISSUE THREAD

**Issue by mmaechtel** [htwg-syslab/nix-expressions#37]
when doing a git push, ssh reports:
```
/etc/ssh/ssh_config line 53: Unsupported option "gssapiauthentication"
/etc/ssh/ssh_config line 54: Unsupported option "gssapidelegatecredentials"
```
the git push works, just the above additional output ...

**Comment by mmaechtel** [comment]
Am i the only one with theses errors?

**Comment by SWW13** [comment]
same here

**Comment by steveeJ** [comment]
I have not been able to reproduce this. Can someone provide a minimal but complete example?

**Comment by SWW13** [comment]
```
user@localhost: $ ssh user@ct-bsys-ss17-0.syslab.in.htwg-konstanz.de

user@ct-bsys-ss17-0: $ labshell bsys

user@ct-bsys-ss17-0 ✓ »shell_bsys@1« $ git clone git@github.com:htwg-syslab-bsys/bsys-ss17-homework.git
Cloning into 'bsys-ss17-homework'...
/etc/ssh/ssh_config line 53: Unsupported option "gssapiauthentication"
/etc/ssh/ssh_config line 54: Unsupported option "gssapidelegatecredentials"
```

**Comment by steveeJ** [comment]
I think it's safe to remove the `gs*` options from */etc/ssh/ssh_config*, since we're not using the builtin kerberos authentication of openssh anywhere. 

@Isele59 we need to 
- [ ] update the template to remove/disable these options
- [ ] change this on *ALL* containers, this is best done via an ansible operation that uses the http://docs.ansible.com/ansible/lineinfile_module.html
