### ISSUE TITLE
nano for labshell

### ISSUE THREAD

**Issue by manuelVo** [htwg-syslab/nix-expressions#79]
I'd really like to have `nano` available in the labshell.

**Comment by steveeJ** [comment]
You are serious, aren't you?

**Comment by manuelVo** [comment]
Yes I am serous. And thanks.

**Comment by steveeJ** [comment]
> Yes I am serous. And thanks.

Of course, it's not a big package anyway :-D

I'm curious, Is there a special use-case you're using nano for? I'm surprised because I don't know anybody who uses nano on a daily basis if there is a choice. Personally, I only use it when there's nothing else available in an environment I can't install vim.

**Comment by manuelVo** [comment]
I usually only use terminal editors for small, quick changes. For those nano works fine, while vim feels like too much overhead (having to type i to enter insert mode, esc to go back to command mode, etc). For anything more sophisticated I prefer an UI.

**Comment by steveeJ** [comment]
Fair enough. BUT: TUI is also a UI ;-)
